# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FHSpQt7m8ke6ryf3QgTtbkuSzQrXXsQ5
"""

# app.py - 信用卡詐欺偵測互動頁面
import streamlit as st
import pandas as pd
import joblib

st.title("💳 信用卡詐欺偵測 Demo")
st.caption("模型：Logistic Regression（class_weight='balanced'），資料：Kaggle/ULB，僅供教育用途")

# 載入訓練好的模型
model = joblib.load('fraud_lr.pkl')

# 調整風險門檻
thr = st.slider("⚠️ 風險門檻 (Threshold)", 0.01, 0.99, 0.5, 0.01)

# 上傳檔案
uploaded_file = st.file_uploader("📂 上傳交易 CSV 檔案（Time, V1-V28, Amount 欄位）", type=["csv"])

if uploaded_file is not None:
    # 讀取檔案
    df = pd.read_csv(uploaded_file)
    st.write("資料筆數：", len(df))

    # 預測
    prob = model.predict_proba(df)[:, 1]  # 詐欺機率
    pred = (prob >= thr).astype(int)       # 根據門檻轉為 0/1

    # 合併結果
    out = df.copy()
    out["fraud_prob"] = prob
    out["prediction"] = pred

    # 顯示前 20 筆
    st.subheader("🔍 預測結果（前 20 筆）")
    st.write(out.head(20))

    # 加下載按鈕
    st.download_button(
        label="💾 下載完整預測結果 CSV",
        data=out.to_csv(index=False),
        file_name="predictions.csv",
        mime="text/csv"
    )